### ISSUE TITLE
python2 dependency

### ISSUE THREAD

**Issue by syheliel** [sslab-gatech/winnie#45]
You should use ` pip2.7.exe install construct pefile==2018.8.8`. Otherwise following error happens
```
    ERROR: Command errored out with exit status 1:
     command: 'c:\python27\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\synsyn\\appdata\\local\\temp\\pip-install-n0hm2c\\pefile\\setup.py'"'"'; __file__='"'"'c:\\users\\synsyn\\appdata\\local\\temp\\pip-install-n0hm2c\\pefile\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\synsyn\appdata\local\temp\pip-pip-egg-info-ieylya'
         cwd: c:\users\synsyn\appdata\local\temp\pip-install-n0hm2c\pefile\
    Complete output (12 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\synsyn\appdata\local\temp\pip-install-n0hm2c\pefile\setup.py", line 86, in <module>
        long_description = "\n".join(_read_doc().split('\n')),
      File "c:\users\synsyn\appdata\local\temp\pip-install-n0hm2c\pefile\setup.py", line 30, in _read_doc
        tree = ast.parse(f.read())
      File "c:\python27\lib\ast.py", line 37, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 3789
        f'Export directory contains more than 10 repeated entries '
                                                                  ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by stong** [comment]
Python3 should be supported now, please reopen if still not working
