### ISSUE TITLE
Synthesizer.py Giving AssertionError

### ISSUE THREAD

**Issue by Austin-Src** [sslab-gatech/winnie#54]
Hey guys, looking for help with the harness generator. I was able to git pin.exe to do all the tracing and give dumps, but when I go to run synthesizer.py I get the below. The example doc shows a -s requires a start function parameter, but both memory addresses and function names seem to fail. One address I gave it moved execution to a different spot (Second trace) but that also failed. Any idea if it's a code problem or a user error? 

Command Line is: python .\synthesizer.py harness -t C:\Users\Guardian\Downloads\pin-3.13-98189-g60a6ef199-msvc-windows\cor1_1\drltrace.25380.log -d C:\Users\Guardian\Downloads\pin-3.13-98189-g60a6ef199-msvc-windows\cor1_1\memdump

Traceback (most recent call last):
  File "C:\Users\Guardian\winnie\harnessgen\synthesizer.py", line 147, in <module>
    main()
  File "C:\Users\Guardian\winnie\harnessgen\synthesizer.py", line 135, in main
    syn = SingleSynthesizer(args.trace_file, args.dump_dir,
  File "C:\Users\Guardian\winnie\harnessgen\common.py", line 480, in __init__
    self.defined_types, self.defined_funcs = self.typedef()
  File "C:\Users\Guardian\winnie\harnessgen\common.py", line 513, in typedef
    assert mod
AssertionError

Traceback (most recent call last):
  File "C:\Users\Guardian\winnie\harnessgen\synthesizer.py", line 147, in <module>
    main()
  File "C:\Users\Guardian\winnie\harnessgen\synthesizer.py", line 135, in main
    syn = SingleSynthesizer(args.trace_file, args.dump_dir,
  File "C:\Users\Guardian\winnie\harnessgen\common.py", line 474, in __init__
    self.start_cid, self.trace_tid = ret_start_point(self.trace_pn, self.start_func.encode())
  File "C:\Users\Guardian\winnie\harnessgen\common.py", line 37, in ret_start_point
    raise Exception("Cannot find the starting function from the trace file")
Exception: Cannot find the starting function from the trace file

**Comment by Austin-Src** [comment]
Discovered the string parsing function didn't like special characters. On to the next issue.
